# Generated by Django 4.1.2 on 2022-10-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="profile_pic",),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="media/default.png", upload_to="profile_images"
            ),
        ),
        migrations.AlterField(
            model_name="profile", name="bio", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
