# Generated by Django 4.1.2 on 2022-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=270, null=True)),
                ('adress', models.CharField(blank=True, max_length=180, null=True)),
                ('site', models.CharField(blank=True, max_length=270, null=True)),
                ('vk', models.CharField(blank=True, max_length=45, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('min_count_of_people', models.IntegerField(blank=True, null=True)),
                ('max_count_of_people', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('other_info', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'places',
                'managed': False,
            },
        ),
    ]
