# Generated by Django 4.1.2 on 2022-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_id_alter_places_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='metro',
            field=models.ManyToManyField(to='core.metro'),
        ),
    ]
