# Generated by Django 4.1.2 on 2022-12-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
        ('core', '0004_metro_places_metro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='other_info',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.authuser')),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='review',
            field=models.ManyToManyField(to='core.review'),
        ),
    ]
