# Generated by Django 4.1.2 on 2022-12-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
        ('core', '0006_remove_places_review_review_date_review_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.profile'),
        ),
    ]
