# Generated by Django 4.1.2 on 2022-12-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_metro_places_metro"),
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default="")),
                ("time", models.CharField(default="", max_length=5)),
                (
                    "from_user_mr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user_mr",
                        to="mainpage.profile",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="core.places",
                    ),
                ),
                (
                    "to_user_mr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user_mr",
                        to="mainpage.profile",
                    ),
                ),
            ],
        ),
    ]
