# Generated by Django 4.1.2 on 2022-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0002_meetingrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrequest",
            name="time",
            field=models.CharField(default="", max_length=10),
        ),
    ]
