# Generated by Django 4.1.2 on 2022-12-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_metro_places_metro"),
        ("mainpage", "0003_alter_meetingrequest_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrequest",
            name="time",
            field=models.TimeField(default="", max_length=10),
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_m", models.DateField(default="")),
                ("time_m", models.TimeField(default="", max_length=10)),
                (
                    "from_user_m",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user_m",
                        to="mainpage.profile",
                    ),
                ),
                (
                    "place_m",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_m",
                        to="core.places",
                    ),
                ),
                (
                    "to_user_m",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user_m",
                        to="mainpage.profile",
                    ),
                ),
            ],
        ),
    ]
