# Generated by Django 4.1.2 on 2022-10-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Places',
        ),
    ]
