# Generated by Django 4.1.2 on 2022-11-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0004_profile_friends_friendrequest"),
        ("mainpage", "0005_delete_places"),
    ]

    operations = []
