# Generated by Django 4.1.2 on 2022-11-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0006_merge_20221119_1434"),
    ]

    operations = [
        migrations.DeleteModel(name="FriendRequest",),
    ]
